# Generated by Django 4.0.1 on 2022-03-22 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='from_user',
            new_name='runner',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='runner',
            new_name='runners',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='training_date',
        ),
        migrations.AddField(
            model_name='report',
            name='training_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 13, 37, 56, 468671)),
        ),
    ]
