# Generated by Django 4.0.1 on 2022-03-23 22:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('running', '0003_alter_report_training_date_alter_workout_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='for_runners',
            field=models.ManyToManyField(blank=True, related_name='runners_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='training_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 0, 39, 14, 93941)),
        ),
    ]
