# Generated by Django 4.0.1 on 2022-03-24 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('running', '0004_workout_for_runners_alter_report_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='training_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 37, 36, 714929)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='for_runners',
            field=models.ManyToManyField(blank=True, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='runners',
            field=models.ManyToManyField(related_name='run_student', through='running.Report', to=settings.AUTH_USER_MODEL),
        ),
    ]
